In [1]:
import numpy as np

In [2]:
array_of_zeros=np.zeros((2,3))
print(array_of_zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [3]:
array_of_zeros=np.zeros([2,3], dtype=np.int16)
print(array_of_zeros)

[[0 0 0]
 [0 0 0]]


In [4]:
array_empty=np.empty((2,3))
print(array_empty)

[[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
array_of_ones=np.ones((2,3))
print(array_of_ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [6]:
type(array_of_ones)

numpy.ndarray

In [9]:
array_of_ones=np.ones([2,3], dtype=np.int16)
print(array_of_ones)

[[1 1 1]
 [1 1 1]]


In [10]:
array_empty=np.empty((2,3))
print(array_empty)

[[1. 1. 1.]
 [1. 1. 1.]]


In [13]:
array_eye=np.eye(4)
print(array_eye)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [19]:
# Req: To print the even number from 2 to 20 using numpy..
array_of_even=np.arange(2,40,2)
print(array_of_even)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]


In [18]:
# Req: To print the even number in decimal from 0 to 2 difference by 0.3  using numpy..
array_of_float=np.arange(0,2,0.3)
print(array_of_float)

[0.  0.3 0.6 0.9 1.2 1.5 1.8]


In [21]:
#Req:Two dimensional array...
array_2d=np.array([(2,4,6),(3,5,7)])
print(array_2d)

[[2 4 6]
 [3 5 7]]


In [22]:
array_2d.shape

(2, 3)

In [26]:
#Req: to create an array of 10 numbers...
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
array_nd=np.arange(10).reshape(2,5)
array_nd

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [28]:
array_nd.shape

(2, 5)

In [29]:
array_nd=np.arange(10).reshape(3,4)
array_nd

ValueError: cannot reshape array of size 10 into shape (3,4)

In [30]:
array_nd=np.arange(10).reshape(5,2)
array_nd

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [32]:
#Req:1d array
a=np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [33]:
a.shape

(6,)

In [35]:
#Req:2d array
b=np.arange(12).reshape(4,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [36]:
b.shape

(4, 3)

In [38]:
#Req:3d array
c=np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [39]:
c.shape

(2, 3, 4)

In [2]:
#Arithmatic operation of numpy...(addition)
import numpy as np
a=np.array([10,10,10])
b=np.array([5,5,5])
a+b

array([15, 15, 15])

In [3]:
#subtraction....
a-b

array([5, 5, 5])

In [4]:
#multiplication
a*b

array([50, 50, 50])

In [5]:
#division
a/b

array([2., 2., 2.])

In [6]:
#comparison...
a<35

array([ True,  True,  True])

In [7]:
b>6

array([False, False, False])

In [15]:
#modifying an existing array rather than create a new one....
a=np.array([10,10,10])
b=np.array([5,5,5])
a+=2
a

array([12, 12, 12])

In [19]:
b+=a
b

array([46, 46, 46])

In [ ]:
#UNARY OPERATOR==>minimum

In [2]:
import numpy as np
ages=np.array([12,15,18,20])
ages.min()

12

In [ ]:
#maximum

In [3]:
ages.max()

20

In [ ]:
#sum of ages..

In [4]:
ages.sum()

65

In [ ]:
# TO FIND SUM OF PERTICULAR ROW AND COLUMN

In [5]:
numbers=np.arange(12).reshape(3,4)
numbers

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
#sum of columns
numbers.sum(axis=0)

array([12, 15, 18, 21])

In [7]:
#sum of rows
numbers.sum(axis=1)

array([ 6, 22, 38])